springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method # alpha
    tags-sorter: alpha
    # Activer le mode "try it out" pour tous les endpoints (désactivée sinon)
    try-it-out-enabled: false
  show-actuator: false # activer sinon pour voir les endpoints actuator dans le swagger.